version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: ticket_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ADMIN1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    hostname: backend
    environment:
      - DATABASE_URL=postgresql://admin:ADMIN1234@postgres:5432/ticket_db
      - TEST_DATABASE_URL=postgresql://admin:ADMIN1234@postgres:5432/ticket_db
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: