version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    environment:
      POSTGRES_DB: ticket_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ADMIN1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: